CREATE TABLE `NOTIFICATION_TYPE` (
	`notification_type_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`type_code`	VARCHAR(50)	NOT NULL	COMMENT 'UNIQUE',
	`type_name`	VARCHAR(100)	NOT NULL,
	`description`	VARCHAR(255)	NOT NULL
);

CREATE TABLE `BOT_POPULARITY_STAT` (
	`stat_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`bot_id`	BIGINT	NOT NULL	COMMENT 'BOT.bot_id',
	`period_type`	VARCHAR(10)	NOT NULL	COMMENT 'MONTH / YEAR',
	`stat_year`	INT	NOT NULL,
	`stat_month`	TINYINT	NOT NULL	DEFAULT 0	COMMENT '연간이면 0',
	`like_count`	INT	NOT NULL	DEFAULT 0,
	`dislike_count`	INT	NOT NULL	DEFAULT 0,
	`popularity_score`	DECIMAL(10,2)	NOT NULL	DEFAULT 0.00,
	`ranking`	INT	NULL	DEFAULT NULL,
	`calculated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `MESSAGE_EMOTION_SCORE` (
	`emotion_score_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`analysis_id`	BIGINT	NOT NULL	COMMENT 'MESSAGE_ANALYSIS.analysis_id',
	`emotion_id`	BIGINT	NOT NULL	COMMENT 'EMOTION_CATEGORY.emotion_id',
	`emotion_score`	DECIMAL(6,4)	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `MESSAGE` (
	`message_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`chat_room_id`	BIGINT	NOT NULL	COMMENT 'CHAT_ROOM.chat_room_id',
	`content`	JSON	NOT NULL,
	`last_message`	TEXT	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `CHAT_ROOM` (
	`chat_room_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`user_id`	BIGINT	NOT NULL	COMMENT 'USER.user_id',
	`bot_id`	BIGINT	NOT NULL	COMMENT 'BOT.bot_id',
	`title`	VARCHAR(100)	NOT NULL,
	`status`	VARCHAR(20)	NOT NULL	DEFAULT 'ACTIVE'	COMMENT 'ACTIVE / ARCHIVED / DELETED',
	`last_message_at`	TIMESTAMP	NULL	DEFAULT NULL	COMMENT '3시간 미작동 체크',
	`archived_at`	TIMESTAMP	NULL,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT 'ON UPDATE CURRENT_TIMESTAMP',
	`background_id`	BIGINT	NOT NULL	COMMENT 'CHAT_BACKGROUND.background_id'
);

CREATE TABLE `USER_ACTIVITY_DAILY` (
	`activity_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`user_id`	BIGINT	NOT NULL	COMMENT 'USER.user_id / UNIQUE',
	`activity_date`	DATE	NOT NULL	COMMENT '하루 1건',
	`login_count`	INT	NOT NULL	DEFAULT 1,
	`activity_score`	INT	NOT NULL	DEFAULT 1,
	`attendance_rewarded`	BOOLEAN	NOT NULL	DEFAULT FALSE,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `NOTIFICATION` (
	`notification_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`content`	VARCHAR(255)	NULL,
	`is_read`	TINYINT	NULL	DEFAULT 0,
	`created_at`	TIMESTAMP	NULL	DEFAULT CURRENT_TIMESTAMP,
	`target_type`	VARCHAR(50)	NULL,
	`target_id`	BIGINT	NULL,
	`user_id`	BIGINT	NOT NULL	COMMENT 'USER.user_id',
	`notification_type_id`	BIGINT	NOT NULL	COMMENT 'NOTIFICATION_TYPE.notification_type_id'
);

CREATE TABLE `SUPPORT_ANSWER` (
	`answer_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`content`	TEXT	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`support_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`user_id`	BIGINT	NOT NULL	COMMENT 'PK, AUTO_INCREMENT'
);

CREATE TABLE `FEED_TRANSACTION` (
	`feed_tx_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`user_id`	BIGINT	NOT NULL	COMMENT 'USER.user_id',
	`bot_id`	BIGINT	NULL	DEFAULT NULL	COMMENT 'BOT.bot_id / NULL 가능',
	`transaction_type`	VARCHAR(20)	NOT NULL	COMMENT 'EARN / USE / ADJUST',
	`amount`	INT	NOT NULL,
	`balance_after`	INT	NOT NULL,
	`reason`	VARCHAR(50)	NOT NULL	COMMENT 'DAILY_ATTENDANCE / FEED_BOT 등',
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `BOT_LETTER` (
	`letter_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`user_id`	BIGINT	NOT NULL	COMMENT 'USER.user_id',
	`bot_id`	BIGINT	NOT NULL	COMMENT 'BOT.bot_id',
	`letter_type`	VARCHAR(30)	NOT NULL	COMMENT 'RECONNECT / MIDNIGHT / HIGH_RISK / GIFT / EMOTION_GROWTH',
	`title`	VARCHAR(200)	NOT NULL,
	`content`	TEXT	NOT NULL,
	`is_read`	BOOLEAN	NOT NULL	DEFAULT FALSE,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`read_at`	TIMESTAMP	NULL	DEFAULT NULL
);

CREATE TABLE `ROLE` (
	`role_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`role_code`	VARCHAR(30)	NOT NULL	COMMENT 'UNIQUE',
	`role_name`	VARCHAR(50)	NOT NULL,
	`description`	VARCHAR(255)	NOT NULL
);

CREATE TABLE `USER_SETTING` (
	`setting_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`user_id`	BIGINT	NOT NULL	COMMENT 'USER.user_id / UNIQUE',
	`satisfaction_popup_enabled`	BOOLEAN	NOT NULL	DEFAULT TRUE,
	`satisfaction_popup_snoozed_until`	TIMESTAMP	NULL	DEFAULT NULL,
	`bot_letter_enabled`	BOOLEAN	NOT NULL	DEFAULT TRUE,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT 'ON UPDATE CURRENT_TIMESTAMP'
);

CREATE TABLE `PASSWORD_RESET_TOKEN` (
	`reset_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`user_id`	BIGINT	NOT NULL	COMMENT 'USER.user_id',
	`token_hash`	VARCHAR(255)	NOT NULL,
	`last_used_at`	TIMESTAMP	NULL	DEFAULT NULL,
	`expired_at`	TIMESTAMP	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `COUNSEL_FEEDBACK` (
	`feedback_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`message_id`	BIGINT	NOT NULL	COMMENT 'MESSAGE.message_id',
	`feedback_type`	VARCHAR(20)	NOT NULL	COMMENT 'HELPFUL / NOT_HELPFUL',
	`comment`	TEXT	NULL	DEFAULT NULL,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `USER_ROLE` (
	`user_role_id`	BIGINT	NOT NULL	COMMENT 'UNIQUE, AUTO_INCREMENT',
	`user_id`	BIGINT	NOT NULL	COMMENT 'USER.user_id',
	`role_id`	BIGINT	NOT NULL	DEFAULT 1	COMMENT 'ROLE.role_id'
);

CREATE TABLE `BOT_MOTION` (
	`motion_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`bot_id`	BIGINT	NOT NULL	COMMENT 'BOT.bot_id',
	`motion_code`	VARCHAR(50)	NOT NULL	COMMENT '예: GREETING',
	`motion_name`	VARCHAR(100)	NOT NULL,
	`motion_group`	VARCHAR(30)	NOT NULL	COMMENT 'COMMON / ANIMAL_IDLE / PRAISE 등',
	`asset_url`	VARCHAR(500)	NOT NULL,
	`unlock_intimacy_level`	INT	NOT NULL	DEFAULT 0,
	`sort_order`	INT	NOT NULL	DEFAULT 0,
	`is_active`	BOOLEAN	NOT NULL	DEFAULT TRUE,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `USER` (
	`user_id`	BIGINT	NOT NULL	COMMENT 'PK, AUTO_INCREMENT',
	`email`	VARCHAR(100)	NOT NULL	COMMENT 'UNIQUE',
	`password`	VARCHAR(255)	NULL	COMMENT '소셜 로그인 시 NULL 가능',
	`nickname`	VARCHAR(30)	NOT NULL,
	`user_name`	VARCHAR(30)	NULL,
	`birth_date`	DATE	NULL,
	`gender`	VARCHAR(10)	NULL,
	`profile_image`	VARCHAR(500)	NULL,
	`login_type`	VARCHAR(20)	NOT NULL	DEFAULT 'LOCAL'	COMMENT 'LOCAL / KAKAO / GOOGLE / NAVER',
	`status`	VARCHAR(20)	NOT NULL	DEFAULT 'ACTIVE'	COMMENT 'ACTIVE / BANNED / DELETED',
	`is_terms_agreed`	BOOLEAN	NOT NULL	DEFAULT FALSE,
	`is_privacy_agreed`	BOOLEAN	NOT NULL	DEFAULT FALSE,
	`is_marketing_agreed`	BOOLEAN	NOT NULL	DEFAULT FALSE,
	`last_login_at`	TIMESTAMP	NULL	DEFAULT NULL,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT 'ON UPDATE CURRENT_TIMESTAMP'
);

CREATE TABLE `COUNSEL_SUMMARY` (
	`analysis_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`user_id`	BIGINT	NOT NULL	COMMENT 'USER.user_id',
	`message_id`	BIGINT	NOT NULL	COMMENT 'UNIQUE',
	`analyzed_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`emotion_score`	DECIMAL(6,4)	NOT NULL
);

CREATE TABLE `AUTO_LOGIN` (
	`auto_login_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`user_id`	BIGINT	NOT NULL	COMMENT 'USER.user_id',
	`token_hash`	VARCHAR(255)	NOT NULL,
	`device_info`	VARCHAR(500)	NULL	DEFAULT NULL,
	`last_used_at`	TIMESTAMP	NULL	DEFAULT NULL,
	`expired_at`	TIMESTAMP	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `CHAT_BACKGROUND` (
	`background_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`name`	VARCHAR(100)	NOT NULL,
	`image_url`	VARCHAR(500)	NOT NULL,
	`unlock_intimacy_level`	INT	NOT NULL	DEFAULT 0,
	`sort_order`	INT	NOT NULL	DEFAULT 0,
	`is_active`	BOOLEAN	NOT NULL	DEFAULT TRUE
);

CREATE TABLE `POST` (
	`post_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`title`	VARCHAR(200)	NOT NULL,
	`content`	TEXT	NOT NULL,
	`like_count`	INT	NOT NULL	DEFAULT 0,
	`dislike_count`	INT	NOT NULL	DEFAULT 0,
	`report_count`	INT	NOT NULL	DEFAULT 0,
	`view_count`	INT	NOT NULL	DEFAULT 0,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT 'ON UPDATE CURRENT_TIMESTAMP',
	`user_id`	BIGINT	NOT NULL	COMMENT 'USER.user_id',
	`category_id`	BIGINT	NOT NULL	COMMENT 'CATEGORY.category_id'
);

CREATE TABLE `USER_INVENTORY` (
	`inventory_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`user_id`	BIGINT	NOT NULL	COMMENT 'USER.user_id / UNIQUE',
	`universal_feed_count`	INT	NOT NULL	DEFAULT 0,
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT 'ON UPDATE CURRENT_TIMESTAMP'
);

CREATE TABLE `POST_IMAGE` (
	`post_image_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`post_id`	BIGINT	NOT NULL	COMMENT 'POST.post_id',
	`image_url`	VARCHAR(500)	NOT NULL,
	`image_order`	INT	NOT NULL	DEFAULT 0,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `BOT_REACTION` (
	`bot_reaction_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`user_id`	BIGINT	NOT NULL	COMMENT 'USER.user_id',
	`bot_id`	BIGINT	NOT NULL	COMMENT 'BOT.bot_id',
	`reaction_type`	VARCHAR(20)	NOT NULL	COMMENT 'LIKE / DISLIKE',
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `SUPPORT` (
	`support_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`user_id`	BIGINT	NOT NULL	COMMENT 'USER.user_id',
	`title`	VARCHAR(200)	NOT NULL,
	`content`	TEXT	NOT NULL,
	`status`	VARCHAR(20)	NOT NULL	DEFAULT 'PENDING'	COMMENT 'PENDING / DONE',
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`support_reason_id`	BIGINT	NOT NULL	COMMENT 'SUPPORT_REASON.support_reason_id'
);

CREATE TABLE `MESSAGE_ANALYSIS` (
	`analysis_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`message_id`	BIGINT	NOT NULL	COMMENT 'MESSAGE.message_id / UNIQUE',
	`dominant_emotion_id`	BIGINT	NULL	COMMENT '기쁨 / 슬픔 / 분노 / 우울 등',
	`risk_level`	TINYINT	NOT NULL	DEFAULT 0	COMMENT '1~5',
	`is_high_risk`	BOOLEAN	NOT NULL	DEFAULT FALSE,
	`recommended_action`	TEXT	NULL	DEFAULT NULL,
	`analyzed_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `COMMENT` (
	`comment_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`content`	TEXT	NOT NULL,
	`like_count`	INT	NOT NULL	DEFAULT 0,
	`report_count`	INT	NOT NULL	DEFAULT 0,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT 'ON UPDATE CURRENT_TIMESTAMP',
	`user_id`	BIGINT	NOT NULL	COMMENT 'USER.user_id',
	`post_id`	BIGINT	NOT NULL	COMMENT 'POST.post_id',
	`parent_comment_id`	BIGINT	NULL	DEFAULT NULL	COMMENT 'COMMENT.comment_id / 대댓글용'
);

CREATE TABLE `USER_BOT_RELATION` (
	`relation_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`user_id`	BIGINT	NOT NULL	COMMENT 'USER.user_id',
	`bot_id`	BIGINT	NOT NULL	COMMENT 'BOT.bot_id',
	`intimacy_score`	INT	NOT NULL	DEFAULT 0,
	`intimacy_level`	INT	NOT NULL	DEFAULT 1,
	`last_fed_at`	TIMESTAMP	NULL	DEFAULT NULL,
	`last_interacted_at`	TIMESTAMP	NULL	DEFAULT NULL,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT 'ON UPDATE CURRENT_TIMESTAMP'
);

CREATE TABLE `SUPPORT_REASON` (
	`support_reason_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`target_type`	VARCHAR(30)	NULL	DEFAULT NULL	COMMENT 'POST/COMMENT/NULL',
	`reason_name`	VARCHAR(100)	NULL	COMMENT '욕설/음란물/광고/결제문의/계정문의/오류문의',
	`is_active`	TINYINT	NOT NULL	DEFAULT 1
);

CREATE TABLE `ADMIN_FAQ` (
	`faq_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`question`	VARCHAR(300)	NOT NULL,
	`answer`	TEXT	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT 'ON UPDATE CURRENT_TIMESTAMP'
);

CREATE TABLE `BOT` (
	`bot_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`name`	VARCHAR(50)	NOT NULL,
	`species_type`	VARCHAR(20)	NOT NULL	COMMENT 'CAT / BEAR / DOG / HAMSTER',
	`avatar_image`	VARCHAR(500)	NULL	DEFAULT NULL,
	`description`	TEXT	NULL	DEFAULT NULL,
	`prompt_text`	TEXT	NOT NULL,
	`selection_preview`	TEXT	NOT NULL,
	`like_count`	INT	NOT NULL	DEFAULT 0	COMMENT '캐시성 집계 컬럼',
	`dislike_count`	INT	NOT NULL	DEFAULT 0	COMMENT '캐시성 집계 컬럼',
	`is_active`	BOOLEAN	NOT NULL	DEFAULT TRUE,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT 'ON UPDATE CURRENT_TIMESTAMP'
);

CREATE TABLE `USER_NOTIFICATION_SETTING` (
	`setting_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`is_enabled`	TINYINT	NOT NULL	DEFAULT 1,
	`notification_type_id`	BIGINT	NOT NULL	COMMENT 'NOTIFICATION_TYPE.notification_type_id, UNIQUE',
	`user_id`	BIGINT	NOT NULL	COMMENT 'USER.user_id, UNIQUE',
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `COMMENT_REACTION` (
	`comment_reaction_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`reaction_type`	VARCHAR(20)	NOT NULL	COMMENT 'LIKE / REPORT',
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`user_id`	BIGINT	NOT NULL	COMMENT 'USER.user_id',
	`comment_id`	BIGINT	NOT NULL	COMMENT 'COMMENT.comment_id'
);

CREATE TABLE `CATEGORY` (
	`category_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`name`	VARCHAR(50)	NOT NULL,
	`display_order`	INT	NOT NULL	DEFAULT 0
);

CREATE TABLE `EMOTION_CATEGORY` (
	`emotion_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`emotion_code`	VARCHAR(20)	NOT NULL	COMMENT 'UNIQUE',
	`emotion_name`	VARCHAR(50)	NOT NULL,
	`is_active`	BOOLEAN	NOT NULL	DEFAULT TRUE
);

CREATE TABLE `ADMIN_NOTICE` (
	`notice_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`title`	VARCHAR(200)	NOT NULL,
	`content`	TEXT	NOT NULL,
	`is_published`	BOOLEAN	NOT NULL	DEFAULT FALSE,
	`published_at`	TIMESTAMP	NULL	DEFAULT NULL,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `POST_REACTION` (
	`post_reaction_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`reaction_type`	VARCHAR(20)	NOT NULL	COMMENT 'LIKE / DISLIKE / REPORT',
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`user_id`	BIGINT	NOT NULL	COMMENT 'USER.user_id',
	`post_id`	BIGINT	NOT NULL	COMMENT 'POST.post_id'
);

CREATE TABLE `SOCIAL_LOGIN` (
	`social_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`user_id`	BIGINT	NOT NULL	COMMENT 'USER.user_id',
	`provider`	VARCHAR(20)	NOT NULL	COMMENT 'provider + provider_user_id UNIQUE',
	`provider_user_id`	VARCHAR(255)	NOT NULL	COMMENT 'provider + provider_user_id UNIQUE',
	`connected_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `SATISFACTION` (
	`satisfaction_id`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`chat_room_id`	BIGINT	NOT NULL	COMMENT 'CHAT_ROOM.chat_room_id',
	`rating`	INT	NOT NULL	COMMENT '1~5',
	`feedback`	TEXT	NULL	DEFAULT NULL,
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE `NOTIFICATION_TYPE` ADD CONSTRAINT `PK_NOTIFICATION_TYPE` PRIMARY KEY (
	`notification_type_id`
);

ALTER TABLE `BOT_POPULARITY_STAT` ADD CONSTRAINT `PK_BOT_POPULARITY_STAT` PRIMARY KEY (
	`stat_id`
);

ALTER TABLE `MESSAGE_EMOTION_SCORE` ADD CONSTRAINT `PK_MESSAGE_EMOTION_SCORE` PRIMARY KEY (
	`emotion_score_id`
);

ALTER TABLE `MESSAGE` ADD CONSTRAINT `PK_MESSAGE` PRIMARY KEY (
	`message_id`
);

ALTER TABLE `CHAT_ROOM` ADD CONSTRAINT `PK_CHAT_ROOM` PRIMARY KEY (
	`chat_room_id`
);

ALTER TABLE `USER_ACTIVITY_DAILY` ADD CONSTRAINT `PK_USER_ACTIVITY_DAILY` PRIMARY KEY (
	`activity_id`
);

ALTER TABLE `NOTIFICATION` ADD CONSTRAINT `PK_NOTIFICATION` PRIMARY KEY (
	`notification_id`
);

ALTER TABLE `SUPPORT_ANSWER` ADD CONSTRAINT `PK_SUPPORT_ANSWER` PRIMARY KEY (
	`answer_id`
);

ALTER TABLE `FEED_TRANSACTION` ADD CONSTRAINT `PK_FEED_TRANSACTION` PRIMARY KEY (
	`feed_tx_id`
);

ALTER TABLE `BOT_LETTER` ADD CONSTRAINT `PK_BOT_LETTER` PRIMARY KEY (
	`letter_id`
);

ALTER TABLE `ROLE` ADD CONSTRAINT `PK_ROLE` PRIMARY KEY (
	`role_id`
);

ALTER TABLE `USER_SETTING` ADD CONSTRAINT `PK_USER_SETTING` PRIMARY KEY (
	`setting_id`
);

ALTER TABLE `PASSWORD_RESET_TOKEN` ADD CONSTRAINT `PK_PASSWORD_RESET_TOKEN` PRIMARY KEY (
	`reset_id`
);

ALTER TABLE `COUNSEL_FEEDBACK` ADD CONSTRAINT `PK_COUNSEL_FEEDBACK` PRIMARY KEY (
	`feedback_id`
);

ALTER TABLE `USER_ROLE` ADD CONSTRAINT `PK_USER_ROLE` PRIMARY KEY (
	`user_role_id`
);

ALTER TABLE `BOT_MOTION` ADD CONSTRAINT `PK_BOT_MOTION` PRIMARY KEY (
	`motion_id`
);

ALTER TABLE `USER` ADD CONSTRAINT `PK_USER` PRIMARY KEY (
	`user_id`
);

ALTER TABLE `COUNSEL_SUMMARY` ADD CONSTRAINT `PK_COUNSEL_SUMMARY` PRIMARY KEY (
	`analysis_id`
);

ALTER TABLE `AUTO_LOGIN` ADD CONSTRAINT `PK_AUTO_LOGIN` PRIMARY KEY (
	`auto_login_id`
);

ALTER TABLE `CHAT_BACKGROUND` ADD CONSTRAINT `PK_CHAT_BACKGROUND` PRIMARY KEY (
	`background_id`
);

ALTER TABLE `POST` ADD CONSTRAINT `PK_POST` PRIMARY KEY (
	`post_id`
);

ALTER TABLE `USER_INVENTORY` ADD CONSTRAINT `PK_USER_INVENTORY` PRIMARY KEY (
	`inventory_id`
);

ALTER TABLE `POST_IMAGE` ADD CONSTRAINT `PK_POST_IMAGE` PRIMARY KEY (
	`post_image_id`
);

ALTER TABLE `BOT_REACTION` ADD CONSTRAINT `PK_BOT_REACTION` PRIMARY KEY (
	`bot_reaction_id`
);

ALTER TABLE `SUPPORT` ADD CONSTRAINT `PK_SUPPORT` PRIMARY KEY (
	`support_id`
);

ALTER TABLE `MESSAGE_ANALYSIS` ADD CONSTRAINT `PK_MESSAGE_ANALYSIS` PRIMARY KEY (
	`analysis_id`
);

ALTER TABLE `COMMENT` ADD CONSTRAINT `PK_COMMENT` PRIMARY KEY (
	`comment_id`
);

ALTER TABLE `USER_BOT_RELATION` ADD CONSTRAINT `PK_USER_BOT_RELATION` PRIMARY KEY (
	`relation_id`
);

ALTER TABLE `SUPPORT_REASON` ADD CONSTRAINT `PK_SUPPORT_REASON` PRIMARY KEY (
	`support_reason_id`
);

ALTER TABLE `ADMIN_FAQ` ADD CONSTRAINT `PK_ADMIN_FAQ` PRIMARY KEY (
	`faq_id`
);

ALTER TABLE `BOT` ADD CONSTRAINT `PK_BOT` PRIMARY KEY (
	`bot_id`
);

ALTER TABLE `USER_NOTIFICATION_SETTING` ADD CONSTRAINT `PK_USER_NOTIFICATION_SETTING` PRIMARY KEY (
	`setting_id`
);

ALTER TABLE `COMMENT_REACTION` ADD CONSTRAINT `PK_COMMENT_REACTION` PRIMARY KEY (
	`comment_reaction_id`
);

ALTER TABLE `CATEGORY` ADD CONSTRAINT `PK_CATEGORY` PRIMARY KEY (
	`category_id`
);

ALTER TABLE `EMOTION_CATEGORY` ADD CONSTRAINT `PK_EMOTION_CATEGORY` PRIMARY KEY (
	`emotion_id`
);

ALTER TABLE `ADMIN_NOTICE` ADD CONSTRAINT `PK_ADMIN_NOTICE` PRIMARY KEY (
	`notice_id`
);

ALTER TABLE `POST_REACTION` ADD CONSTRAINT `PK_POST_REACTION` PRIMARY KEY (
	`post_reaction_id`
);

ALTER TABLE `SOCIAL_LOGIN` ADD CONSTRAINT `PK_SOCIAL_LOGIN` PRIMARY KEY (
	`social_id`
);

ALTER TABLE `SATISFACTION` ADD CONSTRAINT `PK_SATISFACTION` PRIMARY KEY (
	`satisfaction_id`
);

