
export const FALLBACK_HERO_BOTS = [
  {
    key: 'cat',
    name: '냥이',
    typeLabel: '직설형 리포터',
    fallbackLabel: '냥',
    accentColor: '#9A85FF',
    softColor: '#F2ECFF',
    imageUrl: CHARACTER_IMAGE_MAP.cat,
    imagePath: CHARACTER_IMAGE_MAP.cat,
    cardObjectPosition: 'center 14%',
    reportObjectPosition: 'center bottom',
    title: '냥이 피드백',
    summary: '감정을 크게 보기보다 어디서 흔들렸는지 먼저 짚어야 해.',
    bullets: [
      '결과 불안이 감정보다 먼저 커지는 흐름이 보여.',
      '비교가 시작되면 자책으로 이어지는 패턴이 있어.',
      '기준을 조금 낮추면 전체 감정 흐름이 가벼워질 수 있어.',
    ],
    chips: ['현실 점검', '자책 교정', '기준 재정비'],
  },
  {
    key: 'bear',
    name: '곰이',
    typeLabel: '든든한 위로형',
    fallbackLabel: '곰',
    accentColor: '#F3A55C',
    softColor: '#FFF1E4',
    imageUrl: CHARACTER_IMAGE_MAP.bear,
    imagePath: CHARACTER_IMAGE_MAP.bear,
    cardObjectPosition: 'center 18%',
    reportObjectPosition: 'center bottom',
    title: '곰이 리포트',
    summary: '지친 날에는 더 잘하려 하기보다 먼저 버티는 마음을 안아줘야 해.',
    bullets: [
      '무거운 날에도 다시 돌아오려는 힘이 있어.',
      '해결보다 안정이 먼저 필요한 날이 보여.',
      '자기비판을 줄이면 회복도 조금 더 빨라질 수 있어.',
    ],
    chips: ['안정감', '버팀', '따뜻한 위로'],
  },
  {
    key: 'dog',
    name: '강아지',
    typeLabel: '공감·응원형',
    fallbackLabel: '강',
    accentColor: '#7DBBF7',
    softColor: '#ECF6FF',
    imageUrl: CHARACTER_IMAGE_MAP.dog,
    imagePath: CHARACTER_IMAGE_MAP.dog,
    cardObjectPosition: 'center 16%',
    reportObjectPosition: 'center bottom',
    title: '강아지 리포트',
    summary: '큰 결론보다 작은 실행 하나를 같이 잡아주는 게 중요해 보여.',
    bullets: [
      '불안이 올라와도 다시 움직이려는 흐름이 있어.',
      '혼자 다 해결하려 할수록 부담이 커질 수 있어.',
      '작게 시작하면 훨씬 덜 무겁게 움직일 수 있어.',
    ],
    chips: ['공감', '응원', '작은 실행'],
  },
  {
    key: 'hamster',
    name: '햄이',
    typeLabel: '세심한 생활형',
    fallbackLabel: '햄',
    accentColor: '#C6A5FF',
    softColor: '#F4EEFF',
    imageUrl: CHARACTER_IMAGE_MAP.hamster,
    imagePath: CHARACTER_IMAGE_MAP.hamster,
    cardObjectPosition: 'center 12%',
    reportObjectPosition: 'center bottom',
    title: '햄이 리포트',
    summary: '감정이 생활 리듬과 같이 흔들리는 패턴이 보여.',
    bullets: [
      '수면이나 루틴이 흔들리면 감정 반응도 커져.',
      '작은 루틴 하나만 안정돼도 흐름이 정돈될 수 있어.',
      '거창한 다짐보다 생활 단위 회복이 중요해.',
    ],
    chips: ['루틴', '생활 정리', '잔잔한 회복'],
  },
];

export const CHARACTER_IMAGE_MAP = {
  cat: '/images/emotion-report/cat.png',
  bear: '/images/emotion-report/bear.png',
  dog: '/images/emotion-report/dog.png',
  hamster: '/images/emotion-report/hamster.png',
};
